---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check message commits on push
        run: |
          if ! [[ '${{ github.event.commits[0].message }}' =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
            echo "Invalid message commit:"
            echo '${{ github.event.commits[0].message }}'
            exit 1
          fi
        shell: bash {0}