---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check message commits on push
        run: |
          readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq -r ".[].message")
          if ! [[ "${LIST_MESSAGE_COMMITS[0]}" =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
            echo "Invalid message commit:"
            echo "${LIST_MESSAGE_COMMITS[0]}"
            exit 1
          fi
        shell: bash {0}