---
name: Check commit message

on:
  push:
  pull_request:
    branches: [master, main]

jobs:

  lint_message_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Check message commits
        run: |
          echo '${{ toJSON(github.event.commits) }}'
      - uses: actions/github-script@v6
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              console.log(commit);
            }
