---
name: Check commit message

on:
  push:
  pull_request:
    branches: [master, main]

jobs:

  lint_message_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Check message commits
        run: |
          echo '${{ toJSON(github.event.commits) }}' | jq ".[0].message"


