---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Message commits by bash
        run: |
          readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq -r ".[].message")
          for MESSAGE_COMMIT in "${LIST_MESSAGE_COMMITS[@]}"
          do
              echo "message commit:"
              echo "${MESSAGE_COMMIT}"
          done
        shell: bash {0}
      - name: Message commits by script
        uses: actions/github-script@v6
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            var ERROR_FOUND=0;
            for (const commit of commits) {
              var regex = /^([a-z].+(\([a-z].+\))?:\s.*\s\([A-Z].+\)($|\\n.*)\n.*|Merge branch .*)/m;
              var firstline = commit.message.trim().split("\n")
              if(firstline[0].match(regex)){
                console.log("matched");
                console.log(commit.message);
              } else {
                console.log("did not match");
                console.log(commit.message);
                ERROR_FOUND=1;
              }
            }
            if(ERROR_FOUND  == 1){
              core.setFailed("Have invalid message commit");
            }
