---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Message commits on push
        uses: actions/github-script@v6
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              console.log("commit:");
              console.log(commit);
            }
