---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check message commits on push
        run: |
          # shellcheck source=/dev/null
          source ".env.commit_message_regexp"
          set -o errexit   # exit on error
          set -o nounset   # fail if var undefined
          set -o noclobber # don't overwrite exists files via >
          set -o pipefail  # fails if pipes (|) fails
          # set -o xtrace  # debug
          echo ${COMMIT_MESSAGE_REGEXP}
          COMMIT_MESSAGE_REGEXP=$(echo ${COMMIT_MESSAGE_REGEXP} | sed /\\n/\\\\n/)
          echo ${COMMIT_MESSAGE_REGEXP}
          readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq ".[].message")
          ERROR_FOUND=0
          for MESSAGE_COMMIT in "${LIST_MESSAGE_COMMITS[@]}"
          do
            echo "MESSAGE_COMMIT1-1:"
            echo ${MESSAGE_COMMIT:1:-1}
            if ! [[ "${MESSAGE_COMMIT:1:-1}" =~ ${COMMIT_MESSAGE_REGEXP} ]]; then
              echo "Invalid message commit, regexp : ${COMMIT_MESSAGE_REGEXP}"
              echo "${MESSAGE_COMMIT}"
              ERROR_FOUND=1
            fi
          done
          if [ $ERROR_FOUND -eq 1 ]; then
            exit 1
          fi

        shell: bash {0}