---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check message commits on push
        run: |
          echo '${{ github.event.commits[0].message }}'
        shell: bash {0}