---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check message commits on push by script
        uses: actions/github-script@v6
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            var ERROR_FOUND=0;
            for (const commit of commits) {
              const {COMMIT_MESSAGE_REGEXP} = require(".env.commit_message_regexp");
              var firstline = commit.message.trim().split("\n")[0]
              if(!firstline.match(COMMIT_MESSAGE_REGEXP)){
                console.log("message commit does not match regex: " + COMMIT_MESSAGE_REGEXP);
                console.log(commit.message);
                ERROR_FOUND=1;
              }
            }
            console.log(ERROR_FOUND);
            if(ERROR_FOUND == 1){
              core.setFailed("Have invalid message commit");
            }
