---
name: Check commit message

on:
  push:

jobs:

  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Message commits by bash
        run: |
          readarray -t LIST_MESSAGE_COMMITS < <(echo '${{ toJSON(github.event.commits) }}' | jq -r ".[].message")
          for MESSAGE_COMMIT in "${LIST_MESSAGE_COMMITS[@]}"
          do
              echo "message commit:"
              echo "${MESSAGE_COMMIT}"
          done
        shell: bash {0}
      - name: Message commits by script
        uses: actions/github-script@v6
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              console.log("commit:");
              console.log(commit);
            }
